import os

AWS_REGION = os.environ['AWS_REGION']
COGNITO_POOL_ID = os.environ['COGNITO_POOL_ID']
COGNITO_CLIENT_ID = os.environ['COGNITO_CLIENT_ID']
COGNITO_CLIENT_SECRET = os.environ['COGNITO_CLIENT_SECRET']
COGNITO_DOMAIN = os.environ['COGNITO_DOMAIN']
BASE_URL = os.environ['BASE_URL']
